/*
 * OutputCompilingError.java
 *
 * Created on 18. November 2003, 14:38
 */

package de.cismet.cids.admin.importAnt.gui;
import de.cismet.cids.admin.importAnt.*;
/**
 *
 * @author  hell
 */
public class OutputInitializing extends javax.swing.JInternalFrame {
    
    /** Creates new form OutputCompilingError */
    public OutputInitializing(InitializingException iEx) {
        initComponents();
        txtOut.setForeground(java.awt.Color.RED);
        txtOut.append("\nLog -------------\n");
        txtOut.append(iEx.getInitializeLog());
        txtOut.append("\n\n"+iEx.getMessage());
        txtDetail.setText("\n --- Fehlermeldung :\n"+iEx.getCause().toString());
        if (iEx.getCause() instanceof DynamicCompilingException) {
            txtOut.append("\n\n\tEvtl. Fehlerquelle:\n");
            DynamicCompilingException dex=(DynamicCompilingException)iEx.getCause();
            for (int i=0;i<dex.getNumberOfErrors();++i) {
                String[] errorDesc=dex.getErrorDesc(i);
                for (int j=0; j< errorDesc.length;++j) {
                    int x=errorDesc[j].indexOf("by-cids-error-finder:");
                    if(x!=-1) {
                        txtOut.append("\n\t>> "+errorDesc[j].substring(x+"by-cids-error-finder:".length()));
                    }
                }
            }
        }
                  
    }
     public OutputInitializing(String s) {
        initComponents();
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/testok.gif")));
        setTitle("Log");
        txtOut.setForeground(java.awt.Color.BLUE);
        txtOut.append("\nLog -------------\n");
        txtOut.append(s);
        scpDetail.setVisible(false);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tbpMain = new javax.swing.JTabbedPane();
        scpOut = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();
        scpDetail = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fehler");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/errorwarning_tab.gif")));
        scpOut.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        txtOut.setBackground(new java.awt.Color(204, 204, 204));
        txtOut.setEditable(false);
        txtOut.setFont(new java.awt.Font("Dialog", 0, 11));
        txtOut.setForeground(java.awt.Color.red);
        scpOut.setViewportView(txtOut);

        tbpMain.addTab("Log", scpOut);

        scpDetail.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        txtDetail.setBackground(new java.awt.Color(204, 204, 204));
        txtDetail.setEditable(false);
        txtDetail.setFont(new java.awt.Font("Dialog", 0, 11));
        txtDetail.setForeground(java.awt.Color.red);
        scpDetail.setViewportView(txtDetail);

        tbpMain.addTab("Details", scpDetail);

        getContentPane().add(tbpMain, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpDetail;
    private javax.swing.JScrollPane scpOut;
    private javax.swing.JTabbedPane tbpMain;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextArea txtOut;
    // End of variables declaration//GEN-END:variables
    
}
