/*
 * OutputSourceConnection.java
 *
 * Created on 17. November 2003, 18:28
 */

package de.cismet.cids.admin.importAnt.gui;
import de.cismet.common.gui.sqlwizard.*;
import java.sql.*;
/**
 *
 * @author  hell
 */
public class OutputSourceConnection extends javax.swing.JInternalFrame {
    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
    
    /** Creates new form OutputSourceConnection */
    public OutputSourceConnection() {
        initComponents();
        ResultSetTable preview=new ResultSetTable(10,10);
        preview.setEnabled(true);
        preview.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        preview.setCellSelectionEnabled(true);
        
        getContentPane().add(preview, java.awt.BorderLayout.CENTER);
        
    }
     
    public OutputSourceConnection(ResultSet rs, int maxRows) {
        initComponents();
        ResultSetTable preview=new ResultSetTable(10,maxRows);
        preview.setFont(new java.awt.Font("Dialog", 0, 10));
        this.setPreferredSize(new java.awt.Dimension(600,150));
        scpOut.setViewportView(preview);
        try {
            preview.update(rs); 
        } catch (Exception e) {
            log.error("Fehler beim Preview",e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scpOut = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Datenquelle");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/defaults_ps.gif")));
        setMinimumSize(new java.awt.Dimension(200, 150));
        setPreferredSize(new java.awt.Dimension(200, 150));
        scpOut.setPreferredSize(new java.awt.Dimension(200, 150));
        getContentPane().add(scpOut, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpOut;
    // End of variables declaration//GEN-END:variables
    
}
