/*
 * OutputIntermedTable.java
 *
 * Created on 19. November 2003, 19:17
 */

package de.cismet.cids.admin.importAnt.gui;
import de.cismet.cids.admin.importAnt.*;
import javax.swing.ListSelectionModel;
/**
 *
 * @author  hell
 */
public class OutputIntermedTable extends javax.swing.JInternalFrame {
    
    /** Creates new form OutputIntermedTable */
    public OutputIntermedTable(IntermedTable intermed) {
        initComponents();
        tblIntermed.setFont(new java.awt.Font("Dialog", 0, 10));
        setTitle(intermed.getTableName());
        this.tblIntermed.setModel(intermed);
        this.tblIntermed.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pack();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scpMain = new javax.swing.JScrollPane();
        tblIntermed = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/catchup_rls.gif")));
        scpMain.setViewportView(tblIntermed);

        getContentPane().add(scpMain, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpMain;
    private javax.swing.JTable tblIntermed;
    // End of variables declaration//GEN-END:variables
    
}
