/*
 * RuntimeParamEditor.java
 *
 * Created on 19. November 2003, 14:39
 */

package de.cismet.cids.admin.importAnt.gui;

/**
 *
 * @author  hell
 */
public class RuntimeParamEditor extends javax.swing.JPanel {
    
    /** Creates new form RuntimeParamEditor */
    public RuntimeParamEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panMain = new javax.swing.JPanel();
        panProps = new javax.swing.JPanel();
        panPropsTitle = new javax.swing.JPanel();
        lblPropsTitle = new javax.swing.JLabel();
        sepPropsTitle = new javax.swing.JSeparator();
        chkTempDelete = new javax.swing.JCheckBox();
        lblDirTmpClasses = new javax.swing.JLabel();
        txtDirTempClasses = new javax.swing.JTextField();
        cmdDirTempClasses = new javax.swing.JButton();
        panFinalize = new javax.swing.JPanel();
        panFinalizeTitle = new javax.swing.JPanel();
        lnlFinalizeTitle = new javax.swing.JLabel();
        sepFinalizeTitle = new javax.swing.JSeparator();
        lblFinalizeClass = new javax.swing.JLabel();
        txtFinalizeClass = new javax.swing.JTextField();
        cmdFinalizeClass = new javax.swing.JButton();
        lblFinalizeParam = new javax.swing.JLabel();
        txtFinalizeParam = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        panMain.setLayout(new java.awt.GridBagLayout());

        panMain.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        panProps.setLayout(new java.awt.GridBagLayout());

        panPropsTitle.setLayout(new java.awt.GridBagLayout());

        lblPropsTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/prop_ps.gif")));
        lblPropsTitle.setText("Grundeinstellungen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panPropsTitle.add(lblPropsTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        panPropsTitle.add(sepPropsTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panProps.add(panPropsTitle, gridBagConstraints);

        chkTempDelete.setText("Tempor\u00e4re Klassen nicht l\u00f6schen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panProps.add(chkTempDelete, gridBagConstraints);

        lblDirTmpClasses.setText("Verzeichniss f\u00fcr tempor\u00e4re Klassen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panProps.add(lblDirTmpClasses, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panProps.add(txtDirTempClasses, gridBagConstraints);

        cmdDirTempClasses.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panProps.add(cmdDirTempClasses, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panMain.add(panProps, gridBagConstraints);

        panFinalize.setLayout(new java.awt.GridBagLayout());

        panFinalizeTitle.setLayout(new java.awt.GridBagLayout());

        lnlFinalizeTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/admin/res/final_co.gif")));
        lnlFinalizeTitle.setText("Finalizer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panFinalizeTitle.add(lnlFinalizeTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        panFinalizeTitle.add(sepFinalizeTitle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(panFinalizeTitle, gridBagConstraints);

        lblFinalizeClass.setText("Klasse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(lblFinalizeClass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(txtFinalizeClass, gridBagConstraints);

        cmdFinalizeClass.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(cmdFinalizeClass, gridBagConstraints);

        lblFinalizeParam.setText("Parameter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(lblFinalizeParam, gridBagConstraints);

        txtFinalizeParam.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFinalize.add(txtFinalizeParam, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panMain.add(panFinalize, gridBagConstraints);

        add(panMain, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkTempDelete;
    private javax.swing.JButton cmdDirTempClasses;
    private javax.swing.JButton cmdFinalizeClass;
    private javax.swing.JLabel lblDirTmpClasses;
    private javax.swing.JLabel lblFinalizeClass;
    private javax.swing.JLabel lblFinalizeParam;
    private javax.swing.JLabel lblPropsTitle;
    private javax.swing.JLabel lnlFinalizeTitle;
    private javax.swing.JPanel panFinalize;
    private javax.swing.JPanel panFinalizeTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panProps;
    private javax.swing.JPanel panPropsTitle;
    private javax.swing.JSeparator sepFinalizeTitle;
    private javax.swing.JSeparator sepPropsTitle;
    private javax.swing.JTextField txtDirTempClasses;
    private javax.swing.JTextField txtFinalizeClass;
    private javax.swing.JTextArea txtFinalizeParam;
    // End of variables declaration//GEN-END:variables
    
}
