/*
 * JFrame.java
 *
 * Created on 1. M\u00E4rz 2004, 15:12
 */

package de.cismet.cids.admin.serverManagement;
//de.cismet.cids.admin.serverWrapper.Test
/**
 *
 * @author  hell
 */
public class Test extends javax.swing.JFrame {
    long start=System.currentTimeMillis();
    /** Creates new form JFrame */
    public Test() {
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cmdTest = new javax.swing.JButton();
        chkError = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cmdTest.setIcon(new javax.swing.ImageIcon("C:\\Dokumente und Einstellungen\\hell\\Desktop\\navigator img\\graphite\\navigator_icon.gif"));
        cmdTest.setText("Ausgabe Sim");
        cmdTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTestActionPerformed(evt);
            }
        });

        getContentPane().add(cmdTest, java.awt.BorderLayout.CENTER);

        chkError.setText("Error");
        getContentPane().add(chkError, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cmdTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTestActionPerformed
                System.out.println(new java.util.Date(System.currentTimeMillis()-start));

    }//GEN-LAST:event_cmdTestActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       // this.dispose();

    }//GEN-LAST:event_exitForm
    private void lala() throws  Sirius.server.ServerExitError,Sirius.server.ServerExit {
        if (this.chkError.isSelected()) {
            throw new Sirius.server.ServerExitError();
        }
        else {
            throw new Sirius.server.ServerExit();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws  Sirius.server.ServerExitError,Sirius.server.ServerExit {
//        String[] s=new String[0];
//        System.out.println(s[0]);
//        
        Test t=new Test();
         try {java.lang.Thread.sleep(5000);} catch (Exception e) {}
       t.show();
       System.out.println("DA BIN ICH");
         try {java.lang.Thread.sleep(3000);} catch (Exception e) {}
       System.out.println("etwas sp\u00E4ter");
        
    }
    public Test getServerInstance() {
        return this;
    }
    
    public void shutdown() {
        System.out.println("shutdown");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkError;
    private javax.swing.JButton cmdTest;
    // End of variables declaration//GEN-END:variables
    
}
